repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    exclude: ^(\.vscode/|venv/|\.idea/)
    name: isort (python)
- repo: https://github.com/psf/black
  rev: 5.10.1
  hooks:
  - id: black
    exclude: ^(\.vscode/|venv/|\.idea/)
    language_version: python3.10
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies:
      - flake8-black>=0.1.1
    exclude: ^(\.vscode/|venv/|\.idea/)
